REGIONS = [
    "Canada",
    "USA",
    "Mexico",
    "Central America",
    "Brazil",
    "Rest of South America",
    "Western Europe",
    "Central Europe",
    "Ukraine region",
    "Turkey",
    "Northern Africa",
    "Western Africa",
    "Eastern Africa",
    "South Africa",
    "Rest of Souther Africa",
    "Russia Region",
    "Central Asia",
    "Middle east",
    "South Asia",
    "Indonesia Region",
    "India",
    "Rest of South Asia",
    "China Region",
    "Korea Region",
    "Japan",
    "Oceania",
    "World",
]
